# -*- coding: utf-8 -*-
"""OPT PRICER & HEDGER

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SULyqi2StXPxF0p4PF8iKcs8tDErY6WT
"""

import math

# ------------------------------------------------------------
# CDF Approximation — Abramowitz & Stegun
# ------------------------------------------------------------
def normal_cdf(x):
    if x < -8.0: return 0.0
    if x >  8.0: return 1.0
    p  =  0.2316419
    c1 =  0.319381530
    c2 = -0.356563782
    c3 =  1.781477937
    c4 = -1.821255978
    c5 =  1.330274429
    if x >= 0:
        k    = 1.0 / (1.0 + p * x)
        poly = k * (c1 + k * (c2 + k * (c3 + k * (c4 + k * c5))))
        pdf  = math.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)
        return 1.0 - pdf * poly
    else:
        return 1.0 - normal_cdf(-x)


# =========================
# Market data layer  (NEW)
# =========================

import yfinance as yf
import pandas as pd


def fetch_market_data(ticker, vol_window=60):
    """
    Pull spot, risk-free proxy (^IRX 13W T-bill), dividend yield, and realised
    volatility (annualised, close-to-close over `vol_window` days) for a ticker.

    Returns (spot, risk_free, div_yield, sigma).
    Raises ValueError if no usable data is found.
    """
    end   = pd.Timestamp.today()
    start = end - pd.Timedelta(days=vol_window + 60)
    raw   = yf.download(ticker, start=start.strftime("%Y-%m-%d"),
                        end=end.strftime("%Y-%m-%d"),
                        progress=False, auto_adjust=True)
    if raw.empty:
        raise ValueError(f"No data found for ticker '{ticker}'.")

    closes = raw["Close"].squeeze().dropna()
    prices = list(closes.values)
    if len(prices) < 5:
        raise ValueError(f"Not enough price history for '{ticker}'.")
    spot = float(prices[-1])

    # Realised volatility — annualised close-to-close log returns.
    tail  = prices[-(vol_window + 1):] if len(prices) > vol_window + 1 else prices
    lrets = [math.log(tail[i] / tail[i - 1]) for i in range(1, len(tail))]
    m     = sum(lrets) / len(lrets)
    var   = sum((x - m) ** 2 for x in lrets) / (len(lrets) - 1)
    sigma_real = math.sqrt(var * 252)

    # Risk-free proxy: 13-week T-bill yield (^IRX), quoted in percent.
    risk_free = 0.04
    try:
        irx = yf.download("^IRX", period="5d", progress=False, auto_adjust=True)
        if not irx.empty:
            risk_free = float(irx["Close"].dropna().iloc[-1]) / 100.0
    except Exception:
        pass

    # Trailing-12M dividend yield.
    div_yield = 0.0
    try:
        tk   = yf.Ticker(ticker)
        divs = tk.dividends
        if divs is not None and not divs.empty:
            cutoff    = pd.Timestamp.today(tz=divs.index.tz) - pd.DateOffset(years=1)
            last_year = divs[divs.index >= cutoff]
            if not last_year.empty and spot > 0:
                div_yield = float(last_year.sum()) / spot
    except Exception:
        pass

    return spot, risk_free, div_yield, sigma_real


def _ask(prompt, cast=str, default=None, valid=None):
    """Minimal input helper with default + validation."""
    while True:
        raw = input(prompt).strip()
        if raw == "" and default is not None:
            return default
        try:
            val = cast(raw)
        except (ValueError, TypeError):
            print("    ✗ Invalid input."); continue
        if valid is not None and val not in valid:
            print(f"    ✗ Choose one of: {' / '.join(map(str, valid))}"); continue
        return val


def configure_market():
    """
    Interactive configuration.  Returns a dict with keys:
        S, K, tau, r, q, sigma, asset_name

    Per-parameter source choice for S, r, sigma (custom vs real stock).
    K and tau are always custom; when a real stock is used, K is SUGGESTED as a
    ratio of spot but remains editable.
    """
    print("\n" + "=" * 45)
    print("  MARKET CONFIGURATION")
    print("=" * 45)

    use_real = _ask("Use a REAL stock? [y/n] (default n): ",
                    str, default="n", valid={"y", "n"}) == "y"

    asset_name = "CUSTOM"
    spot_real = r_real = q_real = sigma_real = None

    if use_real:
        ticker = _ask("Ticker (e.g. AAPL): ", str, default="AAPL").upper()
        print(f"    Fetching {ticker}…", end="", flush=True)
        spot_real, r_real, q_real, sigma_real = fetch_market_data(ticker)
        print(" ✓")
        asset_name = ticker
        print(f"    Spot        : {spot_real:.4f}")
        print(f"    Risk-free   : {r_real*100:.3f}%  [^IRX]")
        print(f"    Div yield   : {q_real*100:.3f}%  [trailing 12M]")
        print(f"    Realized vol: {sigma_real*100:.2f}%  [60d close-to-close]")

    # ── S : custom or real ────────────────────────────────────────────────────
    if use_real:
        S_cfg = _ask(f"Spot S — use real {spot_real:.4f}? [y/n] (default y): ",
                     str, default="y", valid={"y", "n"})
        S_val = spot_real if S_cfg == "y" else _ask("  Custom S: ", float)
    else:
        S_val = _ask("Spot S (default 105.0): ", float, default=105.0)

    # ── K : ALWAYS custom (suggested as ratio of spot when real) ───────────────
    if use_real:
        ratio = _ask("K as ratio of spot (e.g. 1.05 = 5% OTM call, default 1.00): ",
                     float, default=1.00)
        k_suggest = round(S_val * ratio, 2)
        K_val = _ask(f"Strike K (suggested {k_suggest:.2f}, editable): ",
                     float, default=k_suggest)
    else:
        K_val = _ask("Strike K (default 105.0): ", float, default=105.0)

    # ── tau : ALWAYS custom ────────────────────────────────────────────────────
    tau_val = _ask("Days to expiry tau (default 90): ", int, default=90)

    # ── r : custom or real ─────────────────────────────────────────────────────
    if use_real:
        r_cfg = _ask(f"Rate r — use real {r_real:.4f}? [y/n] (default y): ",
                     str, default="y", valid={"y", "n"})
        r_val = r_real if r_cfg == "y" else _ask("  Custom r: ", float)
    else:
        r_val = _ask("Risk-free r (default 0.03): ", float, default=0.03)

    # ── q : custom or real  ──────────────
    if use_real:
        q_cfg = _ask(f"Div yield q — use real {q_real:.4f}? [y/n] (default y): ",
                     str, default="y", valid={"y", "n"})
        q_val = q_real if q_cfg == "y" else _ask("  Custom q: ", float)
    else:
        q_val = _ask("Dividend yield q (default 0.015): ", float, default=0.015)

    # ── sigma : custom or real ─────────────────────────────────────────────────
    if use_real:
        s_cfg = _ask(f"Vol sigma — use real {sigma_real:.4f}? [y/n] (default y): ",
                     str, default="y", valid={"y", "n"})
        sigma_val = sigma_real if s_cfg == "y" else _ask("  Custom sigma: ", float)
    else:
        sigma_val = _ask("Volatility sigma (default 0.27): ", float, default=0.27)

    return dict(S=S_val, K=K_val, tau=tau_val, r=r_val, q=q_val,
                sigma=sigma_val, asset_name=asset_name)


try:
    _cfg = configure_market()
    S          = _cfg["S"]
    K          = _cfg["K"]
    tau        = _cfg["tau"]
    r          = _cfg["r"]
    q          = _cfg["q"]
    sigma      = _cfg["sigma"]
    ASSET_NAME = _cfg["asset_name"]
except (EOFError, OSError):
    # Non-interactive fallback = original defaults.
    S     = 105.0
    K     = 105.0
    tau   = 90
    r     = 0.03
    q     = 0.015
    sigma = 0.27
    ASSET_NAME = "CUSTOM"


# =========================
# BSM Pricer
# =========================
def bsm_price(S, K, tau, r, q, sigma, option_type="call"):

    tau_y = tau / 365.0

    if tau_y <= 0:
        return max(0.0, S - K) if option_type == "call" else max(0.0, K - S)

    sqrt_tau = math.sqrt(tau_y)
    d1 = (math.log(S / K) + (r - q + 0.5 * sigma * sigma) * tau_y) / (sigma * sqrt_tau)
    d2 = d1 - sigma * sqrt_tau

    if option_type == "call":
        return S * math.exp(-q * tau_y) * normal_cdf(d1) - K * math.exp(-r * tau_y) * normal_cdf(d2)
    elif option_type == "put":
        return K * math.exp(-r * tau_y) * normal_cdf(-d2) - S * math.exp(-q * tau_y) * normal_cdf(-d1)
    else:
        raise ValueError(f"option_type must be 'call' or 'put', got '{option_type}'")


for option_type in ("call", "put"):
    price = bsm_price(S, K, tau, r, q, sigma, option_type)
    label = f"{ASSET_NAME} European {option_type.capitalize()} Option (BSM)"
    print(f"=== {label} ===")
    print(f"S={S:.5f}, K={K:.5f}, tau={tau} days ({tau/365:.5f} yrs), r={r:.5f}, q={q:.5f}, sigma={sigma:.5f}")
    print("-" * 45)
    print(f"Price : {price:.6f}")
    print()

# =========================
# Greeks
# =========================
def numerical_greeks(S, K, tau, r, q, sigma, option_type="call", h=1e-4):

    price = bsm_price(S, K, tau, r, q, sigma, option_type)


    delta = (bsm_price(S+h, K, tau, r, q, sigma, option_type) -
             bsm_price(S-h, K, tau, r, q, sigma, option_type)) / (2*h)


    gamma = (bsm_price(S+h, K, tau, r, q, sigma, option_type) -
             2*price +
             bsm_price(S-h, K, tau, r, q, sigma, option_type)) / (h*h)


    vega  = (bsm_price(S, K, tau, r, q, sigma+h, option_type) -
             bsm_price(S, K, tau, r, q, sigma-h, option_type)) / (2*h) * 0.01


    theta = -(bsm_price(S, K, tau+h, r, q, sigma, option_type) -
             bsm_price(S, K, tau-h, r, q, sigma, option_type)) / (2*h)


    rho   = (bsm_price(S, K, tau, r+h, q, sigma, option_type) -
             bsm_price(S, K, tau, r-h, q, sigma, option_type)) / (2*h) * 0.01


    return price, delta, gamma, vega, theta, rho


for option_type in ("call", "put"):
    price, delta, gamma, vega, theta, rho = numerical_greeks(
        S, K, tau, r, q, sigma, option_type
    )
    label = f"{ASSET_NAME} European {option_type.capitalize()} Option (BSM)"
    print(f"=== {label} ===")
    print(f"S={S:.5f}, K={K:.5f}, tau={tau} days ({tau/365:.5f} yrs), r={r:.5f}, q={q:.5f}, sigma={sigma:.5f}")
    print("-" * 45)
    print(f"Price   : {price:.6f}")
    print(f"Delta   : {delta:.6f}")
    print(f"Gamma   : {gamma:.6f}")
    print(f"Vega    : {vega:.6f}")
    print(f"Theta   : {theta:.6f}")
    print(f"Rho     : {rho:.6f}")

    print()

# =========================
# 3D Plotting
# =========================

import os
import numpy as np
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots

# ── Renderer fix  (Google Colab focus) ──────────────────────────────────────

def _select_renderer():
    try:
        ip = get_ipython()                              # noqa: F821
    except NameError:
        ip = None

    in_notebook = ip is not None and (hasattr(ip, "kernel") or
                                      "IPKernelApp" in getattr(ip, "config", {}))
    if in_notebook:
        return "iframe"

    try:
        import webbrowser
        webbrowser.get()
        return "browser"
    except Exception:
        return "iframe"

pio.renderers.default = _select_renderer()

COLORSCALE_MAP = {
    "delta": "Viridis",
    "gamma": "Plasma",
    "vega" : "Cividis",
    "theta": "RdBu",
    "rho"  : "Magma",
}

EXPORT_DIR = "greeks_export"


# ── Grid ──────────────────────────────────────────────────────────────────────

def build_grids(width_S=0.6, n=60):
    S_min    = max(1.0, S * (1 - width_S))
    S_max    = S * (1 + width_S)
    S_values = np.linspace(S_min, S_max, n)
    tau_values = np.linspace(1.0, tau, n)
    S_grid, tau_grid = np.meshgrid(S_values, tau_values)
    return S_grid, tau_grid, S_min, S_max


def compute_surface(greek, option_type, S_grid, tau_grid):
    """Evaluate one Greek over the (S, tau) grid. tau_grid is in DAYS."""
    Z = np.zeros_like(S_grid)
    greek_idx = {"delta": 1, "gamma": 2, "vega": 3, "theta": 4, "rho": 5}[greek]
    for i in range(S_grid.shape[0]):
        for j in range(S_grid.shape[1]):
            vals = numerical_greeks(
                S_grid[i, j], K, tau_grid[i, j], r, q, sigma, option_type
            )
            Z[i, j] = vals[greek_idx]
    return Z


# ── Single surface ─────────────────────────────────────────────────────────────

def plot_surface_interactive(S_grid, tau_grid, Z, title, colorscale="Viridis"):
    """Interactive 3-D surface. tau_grid is in DAYS (shown on y-axis)."""
    fig = go.Figure(data=[
        go.Surface(
            x=S_grid,
            y=tau_grid,
            z=Z,
            colorscale=colorscale,
            colorbar=dict(title="Value", thickness=15, len=0.7),
            hovertemplate=(
                "S: %{x:.2f}<br>"
                "Days to expiry: %{y:.1f}<br>"
                "Value: %{z:.4f}<extra></extra>"
            ),
        )
    ])
    fig.update_layout(
        title=dict(text=title, font=dict(size=14, family="monospace")),
        scene=dict(
            xaxis_title="Underlying price  S",
            yaxis_title="Days to expiry  τ",
            zaxis_title="Greek value",
            camera=dict(eye=dict(x=1.5, y=1.5, z=1.0)),
            aspectratio=dict(x=1.2, y=1.2, z=0.8),
            xaxis=dict(showbackground=True, backgroundcolor="rgb(240,240,245)"),
            yaxis=dict(showbackground=True, backgroundcolor="rgb(235,240,245)"),
            zaxis=dict(showbackground=True, backgroundcolor="rgb(240,245,245)"),
        ),
        margin=dict(l=0, r=0, t=50, b=0),
        width=850,
        height=620,
    )
    fig.show()
    return fig


# ── Dashboard (5 subplots) ─────────────────────────────────────────────────────

def plot_dashboard_greeks(option_type="call", n=40):
    S_grid, tau_grid, S_min, S_max = build_grids(n=n)
    greeks = list(COLORSCALE_MAP.keys())

    specs = [
        [{"type": "surface"}, {"type": "surface"}, {"type": "surface"}],
        [{"type": "surface"}, {"type": "surface"}, {"type": "surface"}],
    ]
    fig = make_subplots(
        rows=2, cols=3,
        specs=specs,
        subplot_titles=[g.capitalize() for g in greeks] + [""],
    )
    for idx, g in enumerate(greeks):
        Z = compute_surface(g, option_type, S_grid, tau_grid)
        row, col = divmod(idx, 3)
        fig.add_trace(
            go.Surface(
                x=S_grid, y=tau_grid, z=Z,
                colorscale=COLORSCALE_MAP[g],
                showscale=False,
                hovertemplate=(
                    f"<b>{g.capitalize()}</b><br>"
                    "S: %{x:.2f}<br>Days to expiry: %{y:.1f}<br>"
                    "Value: %{z:.4f}<extra></extra>"
                ),
            ),
            row=row + 1, col=col + 1,
        )
    fig.update_layout(
        title=dict(
            text=(
                f"{ASSET_NAME} | Greeks Dashboard | {option_type.capitalize()} | "
                f"S ∈ [{S_min:.2f}, {S_max:.2f}], K={K:.5f}, σ={sigma:.5f}, r={r:.5f}, q={q:.5f}, τ={tau} days"
            ),
            font=dict(size=14, family="monospace"),
        ),
        scene=dict(
            xaxis_title="Underlying price  S",
            yaxis_title="Days to expiry  τ",
            zaxis_title="Greek value",
        ),
        height=800, width=1200,
        margin=dict(l=0, r=0, t=70, b=0),
    )
    fig.show()
    return fig


# ── Save helper ────────────────────────────────────────────────────────────────

def save_figure(fig, filename_base):
    os.makedirs(EXPORT_DIR, exist_ok=True)
    path = os.path.join(EXPORT_DIR, f"{filename_base}.html")
    fig.write_html(path, include_plotlyjs="cdn")
    print(f"  ✓ Saved: {path}")
    return path


# ── Entry point ────────────────────────────────────────────────────────────────

def run_greek_analysis(
    options=("call", "put"),
    greeks=("delta", "gamma", "vega", "theta", "rho"),
    include_dashboard=True,
    n=60,
):
    """Display all Greek surfaces on screen and save them as HTML files."""
    S_grid, tau_grid, S_min, S_max = build_grids(n=n)

    print(f"\n Output folder: {EXPORT_DIR}/\n")

    for opt in options:
        for g in greeks:
            Z = compute_surface(g, opt, S_grid, tau_grid)
            title = (
                f"{ASSET_NAME} | {g.capitalize()} | {opt.capitalize()} | "
                f"S ∈ [{S_min:.2f}, {S_max:.2f}], σ={sigma:.5f}, r={r:.5f}, q={q:.5f}, K={K:.5f}, τ={tau} days"
            )
            fig = plot_surface_interactive(S_grid, tau_grid, Z, title, COLORSCALE_MAP[g])
            save_figure(fig, f"{ASSET_NAME}_{g}_{opt}")

    if include_dashboard:
        for opt in options:
            print(f"\n  → Dashboard {opt}...")
            fig = plot_dashboard_greeks(opt, n=min(n, 40))
            save_figure(fig, f"{ASSET_NAME}_dashboard_{opt}")


run_greek_analysis()



# ══════════════════════════════════════════════════════════════════════════════
# CONTINUATION — HISTORICAL HEDGE SIMULATION  (real stock only)
# ══════════════════════════════════════════════════════════════════════════════


if ASSET_NAME == "CUSTOM":
    print("\n" + "═" * 60)
    print("  Custom underlying selected — no historical price path available.")
    print("  The hedge simulation needs a REAL stock.  Stopping here.")
    print("═" * 60)
else:
    import math as _sim_math

    # ── Simulator BSM / Greeks (per-share) — namespaced ───────────────────────
    def _sim_ncdf(x):
        if x < -8.0: return 0.0
        if x >  8.0: return 1.0
        p = 0.2316419
        c = (0.319381530, -0.356563782, 1.781477937, -1.821255978, 1.330274429)
        if x >= 0:
            k = 1.0 / (1.0 + p * x)
            poly = k * (c[0] + k * (c[1] + k * (c[2] + k * (c[3] + k * c[4]))))
            return 1.0 - _sim_math.exp(-0.5 * x * x) / _sim_math.sqrt(2 * _sim_math.pi) * poly
        return 1.0 - _sim_ncdf(-x)

    def _sim_bsm_price(S, K, tau, r, q, sigma, opt_type):
        if tau <= 0 or sigma <= 0:
            return max(S - K, 0.) if opt_type == "call" else max(K - S, 0.)
        sqt = _sim_math.sqrt(tau)
        d1  = (_sim_math.log(S / K) + (r - q + 0.5 * sigma ** 2) * tau) / (sigma * sqt)
        d2  = d1 - sigma * sqt
        df  = _sim_math.exp(-r * tau)
        dfq = _sim_math.exp(-q * tau)
        if opt_type == "call":
            return S * dfq * _sim_ncdf(d1) - K * df * _sim_ncdf(d2)
        return K * df * _sim_ncdf(-d2) - S * dfq * _sim_ncdf(-d1)

    def _sim_greeks(S, K, tau, r, q, sigma, opt_type, h=1e-4):
        p  = _sim_bsm_price(S,     K, tau, r, q, sigma, opt_type)
        pU = _sim_bsm_price(S + h, K, tau, r, q, sigma, opt_type)
        pD = _sim_bsm_price(S - h, K, tau, r, q, sigma, opt_type)
        return p, (pU - pD) / (2 * h), (pU - 2 * p + pD) / (h * h)

    def _sim_round_to_lot(qty, lot=1):
        return round(qty / lot) * lot

    def _sim_auto_hedge_type(pos_dir, pos_opt):
        return {
            ("short", "call"): ("put",  "long"),
            ("short", "put"):  ("call", "long"),
            ("long",  "call"): ("put",  "short"),
            ("long",  "put"):  ("call", "short"),
        }[(pos_dir, pos_opt)]

    def _sim_rolling_vol(prices_all, sim_start_idx, sim_day, vol_window):
        end_idx   = sim_start_idx + sim_day
        start_idx = max(end_idx - vol_window, 0)
        chunk     = prices_all[start_idx: end_idx + 1]
        if len(chunk) < 3:
            return 0.20
        lrets = [_sim_math.log(chunk[i] / chunk[i - 1]) for i in range(1, len(chunk))]
        m = sum(lrets) / len(lrets)
        v = sum((x - m) ** 2 for x in lrets) / (len(lrets) - 1)
        return _sim_math.sqrt(v * 252)

    def _sim_compute_hedge(port_d, port_g, dh_ps, gh_ps, mult):
        gh_total = mult * gh_ps
        if abs(gh_total) < 1e-14:
            raise ValueError("Hedge option gamma (×multiplier) near zero — choose different strike.")
        w_h = _sim_round_to_lot(-port_g / gh_total)
        w_s = _sim_round_to_lot(-(port_d + w_h * mult * dh_ps))
        return w_h, w_s


    # ── Core simulation + recap + plots ─────────────────
    def _sim_run_simulation(cfg):
        mode       = cfg["mode"]
        h_opt      = cfg["h_opt"]
        pos_sign   = cfg["pos_sign"]
        pos_qty    = cfg["pos_qty"]
        r_         = cfg["risk_free"]
        q_         = cfg["div_yield"]
        mult       = cfg["multiplier"]
        vol_window = cfg["vol_window"]
        prices_all = cfg["prices_all"]
        dates_all  = cfg["dates_all"]

        hedge_days    = cfg["hedge_days"]
        sim_start_idx = len(prices_all) - hedge_days
        prices = prices_all[sim_start_idx:]
        dates  = dates_all[sim_start_idx:]

        DIV = "═" * 76
        print(f"\n{DIV}")
        print(f"  SIMULATION  ·  {cfg['ticker']}  ·  {mode.upper()}")
        print(f"  {len(prices)} days  ({dates[0].date()} → {dates[-1].date()})")
        print(f"  Multiplier: {mult}  |  Vol window: {vol_window}-day fixed rolling")
        print(DIV)

        S0    = prices[0]
        tau0  = cfg["dte"] / 365.
        sigma_ = _sim_rolling_vol(prices_all, sim_start_idx, 0, vol_window)

        p0, d0, g0 = _sim_greeks(S0, cfg["pos_K"], tau0, r_, q_, sigma_, cfg["opt_type"])
        port_d = pos_sign * pos_qty * mult * d0
        port_g = pos_sign * pos_qty * mult * g0

        if h_opt:
            ph0, dh0, gh0 = _sim_greeks(S0, h_opt["K"], tau0, r_, q_, sigma_, h_opt["opt_type"])
            w_h, w_s = _sim_compute_hedge(port_d, port_g, dh0, gh0, mult)
        else:
            ph0 = dh0 = gh0 = 0.0
            w_h = 0.0
            w_s = _sim_round_to_lot(-port_d)

        cash = pos_sign * (-1) * pos_qty * mult * p0
        if h_opt:
            cash -= w_h * mult * ph0
        cash -= w_s * S0

        net_d0 = port_d + (w_h * mult * dh0 if h_opt else 0.0) + w_s
        net_g0 = port_g + (w_h * mult * gh0 if h_opt else 0.0)

        print(f"\nDay 0 setup:")
        print(f"  Spot          : ${S0:.4f}  |  σ={sigma_*100:.2f}%  |  r={r_*100:.3f}%  |  q={q_*100:.3f}%")
        print(f"  Position      : {cfg['pos_dir'].upper()} {pos_qty} {cfg['opt_type']} ctr  "
              f"K={cfg['pos_K']:.2f}  →  ${p0:.4f}/sh  Δ={d0:.6f}  Γ={g0:.6f}")
        print(f"  Port Δ        : {port_d:+.4f}  |  Port Γ : {port_g:+.6f}")
        if h_opt:
            print(f"  Hedge option  : {w_h:+.0f} contracts  [{h_opt['label']}]")
        print(f"  Stock         : {w_s:+.0f} shares  @  ${S0:.4f}")
        print(f"  Cash          : ${cash:,.4f}")
        print(f"  Net Δ         : {net_d0:+.4f}")
        print(f"  Net Γ         : {net_g0:+.6f}")

        cash_unhedged = pos_sign * (-1) * pos_qty * mult * p0
        history = [{
            "day": 0, "date": dates[0].date(), "spot": S0, "sigma": sigma_, "tau": tau0,
            "pos_price": p0, "h_price": ph0,
            "w_h_start": w_h, "w_h_end": w_h, "dw_h": w_h, "opt_cost": -(w_h * mult * ph0),
            "w_s_start": w_s, "w_s_end": w_s, "dw_s": w_s, "stock_cost": -(w_s * S0),
            "net_delta": net_d0, "net_gamma": net_g0,
            "net_delta_start": net_d0, "net_gamma_start": net_g0,
            "net_delta_end": net_d0, "net_gamma_end": net_g0,
            "cash": cash, "mtm_pnl": None, "unhedged_pnl": None,
            "rebalanced": False, "flag": "OPEN",
        }]

        for i in range(1, len(prices)):
            S    = prices[i]
            date = dates[i]
            tau  = max((cfg["dte"] - i) / 365., 1e-6)
            sigma_ = _sim_rolling_vol(prices_all, sim_start_idx, i, vol_window)

            pm, dm, gm = _sim_greeks(S, cfg["pos_K"], tau, r_, q_, sigma_, cfg["opt_type"])
            port_d = pos_sign * pos_qty * mult * dm
            port_g = pos_sign * pos_qty * mult * gm

            w_h_start, w_s_start = w_h, w_s
            if h_opt:
                ph_c, dh_c, gh_c = _sim_greeks(S, h_opt["K"], tau, r_, q_, sigma_, h_opt["opt_type"])
            else:
                ph_c = dh_c = gh_c = 0.0

            dw_h = dw_s = 0.0; opt_cost = stock_cost = 0.0
            rebalanced = False; flag = ""

            if i % cfg["rebal_n"] == 0 and tau > 1e-4:
                if h_opt:
                    if abs(mult * gh_c) < 1e-14:
                        nw_s = _sim_round_to_lot(-(port_d + w_h * mult * dh_c))
                        dw_s = nw_s - w_s; stock_cost = -(dw_s * S); cash += stock_cost
                        w_s = nw_s; flag = "Γ-FLAT"
                    else:
                        nw_h, nw_s = _sim_compute_hedge(port_d, port_g, dh_c, gh_c, mult)
                        dw_h = nw_h - w_h; dw_s = nw_s - w_s
                        opt_cost = -(dw_h * mult * ph_c); stock_cost = -(dw_s * S)
                        cash += opt_cost + stock_cost
                        w_h = nw_h; w_s = nw_s; flag = "REBAL"
                else:
                    nw_s = _sim_round_to_lot(-port_d)
                    dw_s = nw_s - w_s; stock_cost = -(dw_s * S); cash += stock_cost
                    w_s = nw_s; flag = "REBAL"
                rebalanced = True

            if h_opt:
                net_d = port_d + w_h * mult * dh_c + w_s
                net_g = port_g + w_h * mult * gh_c
                mtm   = pos_sign * pos_qty * mult * pm + w_h * mult * ph_c + w_s * S + cash
            else:
                net_d = port_d + w_s; net_g = port_g
                mtm   = pos_sign * pos_qty * mult * pm + w_s * S + cash


            if h_opt:
                net_d_start = port_d + w_h_start * mult * dh_c + w_s_start
                net_g_start = port_g + w_h_start * mult * gh_c
            else:
                net_d_start = port_d + w_s_start; net_g_start = port_g

            unhedged_mtm = pos_sign * pos_qty * mult * pm + cash_unhedged

            history.append({
                "day": i, "date": date.date(), "spot": S, "sigma": sigma_, "tau": tau,
                "pos_price": pm, "h_price": ph_c,
                "w_h_start": w_h_start, "w_h_end": w_h, "dw_h": dw_h, "opt_cost": opt_cost,
                "w_s_start": w_s_start, "w_s_end": w_s, "dw_s": dw_s, "stock_cost": stock_cost,
                "net_delta": net_d, "net_gamma": net_g,
                "net_delta_start": net_d_start, "net_gamma_start": net_g_start,
                "net_delta_end": net_d, "net_gamma_end": net_g,
                "cash": cash, "mtm_pnl": mtm, "unhedged_pnl": unhedged_mtm,
                "rebalanced": rebalanced, "flag": flag,
            })

        # ══════════════════════════════════════════════════════════════════════
        # TABLE 1 — net Δ / Γ at START vs END of each day  (NEW)
        # "start"  = portfolio net Greeks carried in before the day's rebalance
        # "end"    = portfolio net Greeks after the rebalance
        # ══════════════════════════════════════════════════════════════════════
        print(f"\n{DIV}")
        print("  NET Δ / Γ  —  START vs END OF DAY")
        print(DIV)
        Wd, Wdate, Wcol = 4, 12, 16
        hdr = (f"{'Day':>{Wd}} {'Date':>{Wdate}}  "
               f"{'starting delta':>{Wcol}} {'ending delta':>{Wcol}} "
               f"{'starting gamma':>{Wcol}} {'ending gamma':>{Wcol}}")
        print(hdr)
        print("─" * len(hdr))
        for row in history:
            print(f"{row['day']:>{Wd}} {str(row['date']):>{Wdate}}  "
                  f"{row['net_delta_start']:>{Wcol}.4f} "
                  f"{row['net_delta_end']:>{Wcol}.4f} "
                  f"{row['net_gamma_start']:>{Wcol}.6f} "
                  f"{row['net_gamma_end']:>{Wcol}.6f}")
        print("─" * len(hdr))

        # ══════════════════════════════════════════════════════════════════════
        # TABLE 2 — COMPLETE DAILY RECAP  (full ledger, as in the simulator)
        # ══════════════════════════════════════════════════════════════════════
        print(f"\n{DIV}")
        print("  COMPLETE DAILY RECAP")
        print(f"  Position : {cfg['pos_dir'].upper()} {pos_qty} {cfg['opt_type']} ctr  "
              f"(×{mult} = {pos_qty*mult} share-equiv)")
        if h_opt:
            print(f"  Hedge    : {h_opt['label']}  |  netΔ/netΓ = END-OF-DAY after rebalance")
        print(f"  Vol      : {vol_window}-day fixed rolling window")
        print(DIV)

        W = dict(day=4, date=11, spot=8, sig=6, pos_p=8,
                 s_in=9, s_out=9, ds=7, s_cost=12,
                 o_in=8, o_out=8, do=7, o_cost=12,
                 nd=9, ng=12, mtm=13)

        h_a = (
            f"{'':>{W['day']}} {'':>{W['date']}} {'':>{W['spot']}} {'':>{W['sig']}} "
            f"{'Pos':>{W['pos_p']}}  "
            f"{'────────────────── STOCK (shares) ──────────────────':^{W['s_in']+W['s_out']+W['ds']+W['s_cost']+3}}  "
            f"{'────────────── HEDGE OPT (contracts) ────────────':^{W['o_in']+W['o_out']+W['do']+W['o_cost']+3}}  "
            f"{'── Net Greeks ──':^{W['nd']+W['ng']+1}}  "
            f"{'MTM P&L':>{W['mtm']}}"
        )
        h_b = (
            f"{'Day':>{W['day']}} {'Date':>{W['date']}} {'Spot':>{W['spot']}} "
            f"{'σ%':>{W['sig']}} {'OptP':>{W['pos_p']}}  "
            f"{'ini qty':>{W['s_in']}} {'fin qty':>{W['s_out']}} {'Δqty':>{W['ds']}} {'cost($)':>{W['s_cost']}}  "
            f"{'ini qty':>{W['o_in']}} {'fin qty':>{W['o_out']}} {'Δqty':>{W['do']}} {'cost($)':>{W['o_cost']}}  "
            f"{'netΔ':>{W['nd']}} {'netΓ':>{W['ng']}}  "
            f"{'MTM P&L($)':>{W['mtm']}}  flag"
        )
        sep_line = "─" * (len(h_b) + 4)
        print(h_a)
        print(h_b)
        print(sep_line)

        for row in history:
            mtm_s  = f"{row['mtm_pnl']:>+{W['mtm']}.2f}" if row["mtm_pnl"] is not None else f"{'—':>{W['mtm']}}"
            flag_s = f"← {row['flag']}" if row["flag"] else ""
            print(
                f"{row['day']:>{W['day']}} {str(row['date']):>{W['date']}} "
                f"{row['spot']:>{W['spot']}.3f} "
                f"{row['sigma']*100:>{W['sig']}.2f}  "
                f"{row['pos_price']:>{W['pos_p']}.4f}  "
                f"{row['w_s_start']:>+{W['s_in']}.0f} "
                f"{row['w_s_end']:>+{W['s_out']}.0f} "
                f"{row['dw_s']:>+{W['ds']}.0f} "
                f"{row['stock_cost']:>+{W['s_cost']}.2f}  "
                f"{row['w_h_start']:>+{W['o_in']}.2f} "
                f"{row['w_h_end']:>+{W['o_out']}.2f} "
                f"{row['dw_h']:>+{W['do']}.2f} "
                f"{row['opt_cost']:>+{W['o_cost']}.2f}  "
                f"{row['net_delta']:>{W['nd']}.4f} "
                f"{row['net_gamma']:>{W['ng']}.7f}  "
                f"{mtm_s}  {flag_s}"
            )
        print(sep_line)

        # ── Final summary ─────────────────────────────────────────────────────
        fin = history[-1]; ini = history[0]
        n_rb = sum(1 for h in history if h["rebalanced"])
        pnl  = [h["mtm_pnl"] for h in history if h["mtm_pnl"] is not None]
        print(f"\n{DIV}")
        print(f"  FINAL SUMMARY  ·  {mode.upper()}  ·  {cfg['ticker']}")
        print(DIV)
        print(f"  Trading days          : {len(history)}")
        print(f"  Rebalances            : {n_rb}  (every {cfg['rebal_n']} day(s))")
        print(f"  Initial spot          : ${ini['spot']:.4f}")
        print(f"  Final   spot          : ${fin['spot']:.4f}  "
              f"({(fin['spot']/ini['spot']-1)*100:+.2f}%)")
        print(f"  Position              : {cfg['pos_dir'].upper()} {pos_qty} "
              f"{cfg['opt_type']} ctr  K={cfg['pos_K']:.2f}")
        if h_opt:
            print(f"  Hedge option          : {h_opt['label']}")
            print(f"  Hedge contracts (fin) : {fin['w_h_end']:+.0f}")
        print(f"  Stock shares (final)  : {fin['w_s_end']:+.0f}")
        if pnl:
            print(f"  MTM P&L (final)       : ${fin['mtm_pnl']:+,.4f}")
            print(f"  MTM P&L max / min     : ${max(pnl):+,.4f}  /  ${min(pnl):+,.4f}")
        print(f"  Final netΔ            : {fin['net_delta']:+.4f}")
        print(f"  Final netΓ            : {fin['net_gamma']:+.6f}")
        print()

        _sim_plot_pnl(history, cfg)
        _sim_plot_pnl_comparison(history, cfg)
        return history

    # ── P&L plots (namespaced) ────────────────────────────────────────────────
    def _sim_plot_pnl(history, cfg):
        try:
            import matplotlib.pyplot as plt
            import matplotlib.dates as mdates
            from matplotlib.ticker import FuncFormatter
        except ImportError:
            print("  ⚠  matplotlib not installed — skipping plot."); return
        h_opt = cfg["h_opt"]
        rows = [r for r in history if r["mtm_pnl"] is not None]
        if not rows:
            print("  ⚠  No P&L points to plot."); return
        dates_p = [r["date"] for r in rows]
        pnl = [r["mtm_pnl"] for r in rows]; nd = [r["net_delta"] for r in rows]
        ng = [r["net_gamma"] for r in rows]; sig = [r["sigma"]*100 for r in rows]
        rebal = [r["date"] for r in history if r["rebalanced"]]
        fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(13, 9), sharex=True,
                                            gridspec_kw={"height_ratios": [3, 2, 1.5]})
        fig.suptitle(f"Hedging P&L  ·  {cfg['ticker']}  ·  {cfg['mode'].upper()}\n"
                     f"{cfg['pos_dir'].upper()} {cfg['pos_qty']} {cfg['opt_type']} "
                     f"K={cfg['pos_K']:.2f}  |  "
                     + (f"Hedge: {h_opt['label']}" if h_opt else "No hedge option"),
                     fontsize=11, y=0.98)
        def _rb(ax):
            for rd in rebal: ax.axvline(rd, color="grey", lw=0.5, ls="--", alpha=0.4)
        ax1.axhline(0, color="black", lw=0.8, alpha=0.6); _rb(ax1)
        ax1.fill_between(dates_p, pnl, 0, where=[v >= 0 for v in pnl], alpha=0.25, color="seagreen", label="Gain")
        ax1.fill_between(dates_p, pnl, 0, where=[v < 0 for v in pnl], alpha=0.25, color="crimson", label="Loss")
        ax1.plot(dates_p, pnl, color="steelblue", lw=1.6, label="MTM P&L")
        ax1.set_ylabel("MTM P&L ($)", fontsize=9)
        ax1.yaxis.set_major_formatter(FuncFormatter(lambda x, _: f"${x:,.0f}"))
        ax1.legend(fontsize=8, loc="upper left"); ax1.grid(axis="y", ls=":", alpha=0.4)
        ax2.axhline(0, color="black", lw=0.8, alpha=0.6); _rb(ax2)
        ax2.plot(dates_p, nd, color="darkorange", lw=1.4, label="net Δ (shares)")
        ax2r = ax2.twinx(); ax2r.plot(dates_p, ng, color="mediumpurple", lw=1.2, ls="--", label="net Γ")
        ax2r.set_ylabel("net Γ", fontsize=8, color="mediumpurple")
        ax2r.tick_params(axis="y", labelcolor="mediumpurple", labelsize=7)
        ax2.set_ylabel("net Δ (shares)", fontsize=9)
        l1, lab1 = ax2.get_legend_handles_labels(); l2, lab2 = ax2r.get_legend_handles_labels()
        ax2.legend(l1 + l2, lab1 + lab2, fontsize=8, loc="upper left"); ax2.grid(axis="y", ls=":", alpha=0.4)
        _rb(ax3); ax3.plot(dates_p, sig, color="teal", lw=1.2)
        ax3.fill_between(dates_p, sig, alpha=0.15, color="teal")
        ax3.set_ylabel("σ (%)", fontsize=9); ax3.set_xlabel("Date", fontsize=9)
        ax3.grid(axis="y", ls=":", alpha=0.4)
        ax3.xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))
        fig.autofmt_xdate(rotation=35, ha="right"); plt.tight_layout(); plt.show()

    def _sim_plot_pnl_comparison(history, cfg):
        try:
            import matplotlib.pyplot as plt
            import matplotlib.dates as mdates
            from matplotlib.ticker import FuncFormatter
        except ImportError:
            print("  ⚠  matplotlib not installed — skipping comparison plot."); return
        rows = [r for r in history if r["mtm_pnl"] is not None and r.get("unhedged_pnl") is not None]
        if not rows:
            print("  ⚠  No comparison P&L points to plot."); return
        dates_p = [r["date"] for r in rows]
        hedged = [r["mtm_pnl"] for r in rows]; unhedged = [r["unhedged_pnl"] for r in rows]
        spots = [r["spot"] for r in rows]
        advantage = [h - u for h, u in zip(hedged, unhedged)]
        h_opt = cfg["h_opt"]; mode_label = cfg["mode"].upper()
        pos_label = f"{cfg['pos_dir'].upper()} {cfg['pos_qty']} {cfg['opt_type']} K={cfg['pos_K']:.2f}"
        hedge_label = h_opt["label"] if h_opt else "stock only"
        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(13, 7), sharex=True,
                                       gridspec_kw={"height_ratios": [3, 1.5]})
        fig.suptitle((f"Hedged vs Unhedged P&L  ·  {cfg['ticker']}  ·  {mode_label}\n"
                      f"{pos_label}  |  Hedge: {hedge_label}"), fontsize=11, y=0.98)
        ax1.axhline(0, color="black", lw=0.8, alpha=0.5)
        ax1.fill_between(dates_p, hedged, unhedged, where=[a >= 0 for a in advantage],
                         alpha=0.18, color="seagreen", label="Hedge advantage")
        ax1.fill_between(dates_p, hedged, unhedged, where=[a < 0 for a in advantage],
                         alpha=0.18, color="crimson", label="Hedge cost")
        ax1.plot(dates_p, unhedged, color="crimson", lw=1.4, ls="--", label="Unhedged P&L")
        ax1.plot(dates_p, hedged, color="steelblue", lw=1.8, label=f"Hedged P&L ({mode_label})")
        ax1.annotate(f"${hedged[-1]:+,.0f}", xy=(dates_p[-1], hedged[-1]), xytext=(8, 0),
                     textcoords="offset points", fontsize=8, color="steelblue", va="center")
        ax1.annotate(f"${unhedged[-1]:+,.0f}", xy=(dates_p[-1], unhedged[-1]), xytext=(8, 0),
                     textcoords="offset points", fontsize=8, color="crimson", va="center")
        ax1.set_ylabel("MTM P&L ($)", fontsize=9)
        ax1.yaxis.set_major_formatter(FuncFormatter(lambda x, _: f"${x:,.0f}"))
        ax1.legend(fontsize=8, loc="upper left"); ax1.grid(axis="y", ls=":", alpha=0.4)
        ax2.plot(dates_p, spots, color="goldenrod", lw=1.4, label="Spot price")
        ax2.axhline(cfg["pos_K"], color="red", lw=0.8, ls=":", label=f"Strike K={cfg['pos_K']:.2f}")
        ax2.set_ylabel("Spot ($)", fontsize=9)
        ax2.yaxis.set_major_formatter(FuncFormatter(lambda x, _: f"${x:,.0f}"))
        ax2.legend(fontsize=8, loc="upper left"); ax2.grid(axis="y", ls=":", alpha=0.4)
        ax2.set_xlabel("Date", fontsize=9)
        ax2.xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))
        fig.autofmt_xdate(rotation=35, ha="right"); plt.tight_layout(); plt.show()

    # ── Fetch the FULL price history for the chosen ticker ────────────────────
    def _sim_fetch_history(ticker, lookback_days=252, vol_window=60):
        end   = pd.Timestamp.today()
        start = end - pd.Timedelta(days=lookback_days + 30)
        raw   = yf.download(ticker, start=start.strftime("%Y-%m-%d"),
                            end=end.strftime("%Y-%m-%d"),
                            progress=False, auto_adjust=True)
        if raw.empty:
            raise ValueError(f"No data found for '{ticker}'.")
        closes = raw["Close"].squeeze().dropna()
        prices_all = [float(x) for x in closes.values]
        dates_all  = list(closes.index)
        if len(prices_all) < vol_window + 2:
            raise ValueError(f"Not enough history (need ≥ {vol_window+2} bars).")
        return prices_all, dates_all

    # ── ASK: hedge configuration (reuse base _ask) ────────────────────────────
    print("\n" + "═" * 60)
    print(f"  HISTORICAL HEDGE SIMULATION  ·  {ASSET_NAME}")
    print(f"  (strike K={K:.5f} and DTE={tau}d reused from the pricer)")
    print("═" * 60)

    _mode = _ask("Hedging mode [delta / delta_gamma] (default delta_gamma): ",
                 str, default="delta_gamma", valid={"delta", "delta_gamma"})
    _mult = _ask("Contract multiplier (default 100): ", int, default=100)
    _pos_dir = _ask("Position direction [long / short] (default short): ",
                    str, default="short", valid={"long", "short"})
    _pos_opt = _ask("Position option type [call / put] (default call): ",
                    str, default="call", valid={"call", "put"})
    _pos_qty = max(1, _ask("Number of contracts (default 10): ", int, default=10))
    _dte = int(tau)
    _hedge_days = _ask(f"Trading days to simulate (default {_dte}): ", int, default=_dte)
    _rebal_n = _ask("Rebalance every N trading days (default 1): ", int, default=1)
    _pos_sign = 1 if _pos_dir == "long" else -1

    # ── ASK: second hedge option (only for delta_gamma) ───────────────────────
    _h_opt = None
    if _mode == "delta_gamma":
        _ht_auto, _hd_auto = _sim_auto_hedge_type(_pos_dir, _pos_opt)
        print("-" * 60)
        print("  Second option (gamma hedge)")
        print(f"  Auto-selected by rule: {_hd_auto.upper()} {_ht_auto.upper()}  "
              f"({_pos_dir} {_pos_opt} → {_hd_auto} {_ht_auto})")
        _h_type = _ask(f"Hedge type [call / put] (default {_ht_auto}): ",
                       str, default=_ht_auto, valid={"call", "put"})
        _h_dir  = _ask(f"Hedge direction [long / short] (default {_hd_auto}): ",
                       str, default=_hd_auto, valid={"long", "short"})
        _atm_default = round(S * _sim_math.exp((r - q) * (_dte / 365.)), 2)
        _h_K = _ask(f"Hedge strike (default {_atm_default:.5f}, near-ATM): ",
                    float, default=_atm_default)
        _h_opt = dict(opt_type=_h_type, dir=_h_dir,
                      sign=(1 if _h_dir == "long" else -1),
                      K=_h_K, label=f"{_h_dir} {_h_type} K={_h_K:.2f}")

    # ── Fetch history and assemble the cfg the simulator expects ──────────────
    print(f"\n    Fetching price history for {ASSET_NAME}…", end="", flush=True)
    _prices_all, _dates_all = _sim_fetch_history(ASSET_NAME)
    print(" ✓")

    _vol_window = 60
    _hedge_days = max(1, min(_hedge_days, len(_prices_all)))
    if len(_prices_all) - _hedge_days < _vol_window:
        _vol_window = max(len(_prices_all) - _hedge_days, 5)

    _cfg_sim = dict(
        mode=_mode, ticker=ASSET_NAME,
        prices_all=_prices_all, dates_all=_dates_all,
        risk_free=r, div_yield=q, sigma=sigma,
        opt_type=_pos_opt, pos_dir=_pos_dir, pos_sign=_pos_sign,
        pos_qty=_pos_qty, pos_K=K, dte=_dte,
        h_opt=_h_opt, hedge_days=_hedge_days, rebal_n=_rebal_n,
        multiplier=_mult, vol_window=_vol_window,
    )

    # ── Run the historical simulation (inline, namespaced) ────────────────────
    _sim_run_simulation(_cfg_sim)